name: Continuous integration
on:
  release:
    types: [created]
  push:
    branches:
      - '**'

env:
  # renovate: datasource=npm depName=npm
  NPM_VERSION: '11'

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@${{ env.NPM_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Lint
        run: npm run lint

  build-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@${{ env.NPM_VERSION }}

      - name: Install plugin dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Install example dependencies
        run: npm ci
        working-directory: example

      - name: Build example
        run: npm run build
        working-directory: example

  verify-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@${{ env.NPM_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version-file: '.java-version'

      - name: Verify
        run: npm run verify:android

  verify-ios:
    runs-on: macos-latest
    steps:
      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_26.0.app

      - name: Prepare simulator runtime
        run: |
          xcrun simctl list > /dev/null
          xcodebuild -downloadPlatform iOS

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@${{ env.NPM_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Verify
        run: npm run verify:ios

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [lint, verify-ios, verify-android, build-example]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Upgrade npm
        run: npm install -g npm@${{ env.NPM_VERSION }}

      - uses: microbit-foundation/npm-package-versioner-action@v3

      - name: Install plugin dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - run: npm pack
      - uses: actions/upload-artifact@v7
        with:
          name: npm-tarball
          path: '*.tgz'
          if-no-files-found: error
          retention-days: 1

  publish:
    needs: release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: npm-tarball
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@${{ env.NPM_VERSION }}
      - run: npm stage publish --allow-file=all ./*.tgz
